# Generated by Django 4.1.6 on 2023-02-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0002_remove_useraccount_is_dev_remove_useraccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_dev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
